version: "3.3"
services:
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: thisisasupersecurepassword
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  proxy:
    build: ./proxy
    ports:
      - "80:80"