"""added sunlight and water to plants

Revision ID: eb6e3881fa63
Revises: 85b6c110b98a
Create Date: 2024-02-17 16:15:17.836911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6e3881fa63'
down_revision = '85b6c110b98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunlight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('water', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('water')
        batch_op.drop_column('sunlight')

    # ### end Alembic commands ###
